### ISSUE TITLE
Authenticator doesn't timeout

### ISSUE THREAD

**Issue by am4c130d** [bitwarden/authenticator-android#204]
### Steps To Reproduce

1. Open/unlock authenticator
2. Allow phone to timeout/sleep
3. Unlock phone
4. Authenticator is still unlocked and displaying codes

### Expected Result

I expect the authenticator to timeout when the phone times out and to challenge me to re-enter my credentials (password, pin, biometric etc.) when I want to access it again

### Actual Result

Authenticator never times out and has to be manually closed

### Build Version

2024.6.2 (340)

### Environment Details

Pixel 6a
Android version 14
Build Number AP2A.240905.003.F1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
