### ISSUE TITLE
Google Authenticator does not work (despite saying it was imported successfully)

### ISSUE THREAD

**Issue by omentic** [bitwarden/authenticator-android#292]
### Steps To Reproduce

1. Export a code from Google Authenticator to their QR code format.
2. Take a screenshot of the QR code, or otherwise move it to a different device
3. Scan the QR code in Bitwarden Authenticator's interface

### Expected Result

The code should be imported.

### Actual Result

The code is not imported. Despite this, a little popup saying "Authenticator code added" is displayed. 

### Screenshots or Videos

I can't attach screenshots of the behavior, as the authenticator app appears to block screenshots.

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin with the application experiencing a behavior issue.

Please try reinstalling the Bitwarden Authenticator app by following the below steps:

 -  Uninstall the Bitwarden Authenticator app
 -  Restart the device (perform a full power cycle, shutting the device down completely and then restarting it)
 -  Reinstall Bitwarden Authenticator app

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by omentic** [comment]
Hi @rmcdowell-bitwarden, what behavior did you observe?

**Comment by rmcdowell-bitwarden** [comment]
I was able to import all test items from my Google Authenticator app into my Bitwarden Authenticator successfully. I tried multiple individual tests followed by group tests to confirm that the import process was functioning correctly.
